### ISSUE TITLE
Running `drs_downloader terra` outputs a stack trace and exits

### ISSUE THREAD

**Issue by mbaumann-broad** [anvilproject/drs_downloader#43]
# Current Behavior 
Running:
```
drs_downloader terra
```
outputs the following stack trace and exists:
```
Traceback (most recent call last):
  File "drs_downloader/cli.py", line 383, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "drs_downloader/cli.py", line 146, in terra
  File "pathlib.py", line 960, in __new__
  File "pathlib.py", line 594, in _from_parts
  File "pathlib.py", line 578, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not NoneType
[7047] Failed to execute script 'cli' due to unhandled exception!
```

# Desired Behavior
Running:
```
drs_downloader terra
```
has the same result as running:
```
drs_downloader terra --help
```

# Found In
drs_downloader v0.1.5-rc.11 running on macOS

**Comment by matthewpeterkort** [comment]
Current behavior from: https://github.com/anvilproject/drs_downloader/releases/tag/v0.1.5-rc.14
```
(venv) peterkor@RNB11238 drs_downloader % /Applications/drs_downloader terra                                                                       
Usage: drs_downloader terra [OPTIONS]
Try 'drs_downloader terra --help' for help.

Error: Missing option '--manifest-path' / '-m'.
(venv) peterkor@RNB11238 drs_downloader % 
(venv) peterkor@RNB11238 drs_downloader % /Applications/drs_downloader terra --help
Usage: drs_downloader terra [OPTIONS]

  Copy files from terra.bio

Options:
  -v, --verbose               Display every logger
  -d, --destination-dir TEXT  Destination directory.  [default: /Users/peterko
                              r/Desktop/downloadger/drs_downloader; required]
  -m, --manifest-path TEXT    Path to manifest tsv.  [required]
  --drs-column-name TEXT      The column header in the TSV file associated
                              with the DRS URIs.Example: pfb:ga4gh_drs_uri
  -u, --user-project TEXT     This option is used to specify the Terra
                              Workspace           Google project id if the
                              requester is paying for the download
  --duplicate                 This flag is used to specify wether     or not
                              to download the file again if it already exists
                              in the directoryExample: True
  --string-mode TEXT          This option is used when you want to run the
                              downloader with URIS          that you provide
                              in string form with uris seperated by commas the
                              command line. ex: 'uri1, uri2, uri3'
  --help                      Show this message and exit.
(venv) peterkor@RNB11238 drs_downloader % 
```
